#!/bin/bash

APPIMAGENAME="TrashCan"
WHERE=${WHERE:-"/tmp/qtchroot"}
PROJECTFOLDER=..
ELFLOG=/tmp/linked.log
LIBS=/tmp/libs
:>$ELFLOG
:>$LIBS
rm ./${APPIMAGENAME}.AppImage

if [[ ! -e ./runtime-x86_64 ]];then
	wget "https://github.com/AppImage/type2-runtime/releases/download/continuous/runtime-x86_64"
fi

rm -r ${WHERE}
mkdir -p ${WHERE}/usr/bin
mkdir -p ${WHERE}/lib

ln -sfv ../lib ${WHERE}/usr/lib
ln -sfv ../lib ${WHERE}/usr/lib32
ln -sfv ../lib ${WHERE}/usr/lib64

ln -sfv lib ${WHERE}/lib32
ln -sfv lib ${WHERE}/lib64

ln -sfv usr/bin ${WHERE}/bin

pushd ${PROJECTFOLDER}
	make local||exit 100
	cp trashcan user-trash-full.png user-trash.png ${WHERE}/usr/bin
	:>$ELFLOG
popd

cp --parents -rp /usr/lib/qt6/plugins/xcbglintegrations ${WHERE}
cp --parents -rp /usr/lib/qt6/plugins/platforms/libqxcb.so  ${WHERE}
cp --parents -rp /usr/lib64/qt6/plugins/platformthemes/libqt6ct.so  ${WHERE}
cp --parents -rp /usr/lib64/qt6/plugins/styles/libqt6ct-style.so  ${WHERE}

#cp --parents -rp /usr/lib/qt6/plugins/assetimporters ${WHERE}
#cp --parents -rp /usr/lib/qt6/plugins/sqldrivers ${WHERE}
cp  /usr/sbin/dbus-launch /usr/bin/dbus-daemon ${WHERE}/bin

while read
	do
		if file "$REPLY"|grep --quiet -i "ELF" ;then
			ldd "$REPLY" |awk -F"=>" '{print $2}'|awk  '{print $1}' >> $ELFLOG
		fi
	done< <(find $WHERE -type f)

sort -u $ELFLOG > $LIBS

sed -i '/^$/d' $LIBS
sed -i '/^.*ld-linux-x86-64.so.*$/d' $LIBS
sed -i '/^.*libc.so.*$/d' $LIBS

cat $LIBS|while read
	do
		if [[ -h "$REPLY" ]];then
			link=$(readlink -f "$REPLY"||true)||true
			cp --parents -P $link ${WHERE}||true
		fi
		cp --parents -P "$REPLY" ${WHERE}||true
	done

APPIMAGEFOLDER=$WHERE
APPNAME="${APPIMAGENAME,,}"
ICONPATH="${PROJECTFOLDER}/user-trash.png"
ICONNAME=$(basename "${ICONPATH}")

cp "${ICONPATH}" "${APPIMAGEFOLDER}/${ICONNAME}"
cat >${APPIMAGEFOLDER}/${APPNAME}.desktop <<EOF
[Desktop Entry]
Type=Application
Name=${APPNAME}
Exec=${APPNAME}
Icon=${ICONNAME%.?*}
Categories=Utility;
EOF

cat >${APPIMAGEFOLDER}/AppRun <<EOF
#!/bin/bash

export LD_LIBRARY_PATH="\$APPDIR/lib:\$APPDIR/usr/lib:/lib:usr/lib"
export PATH="\${APPDIR}/bin:\${PATH}"
export QT_QPA_PLATFORMTHEME=qt6ct
export QT_PLUGIN_PATH="\$APPDIR/usr/lib/qt6/plugins:\$APPDIR/usr/lib/qt6/:\$APPDIR/usr/lib/qt6/plugins/xcbglintegrations:\$APPDIR/usr/lib/qt6/plugins/platforms:\$APPDIR/usr/lib/qt6/plugins/styles:\$APPDIR/usr/lib/qt6/plugins/platformthemes"

exec /bin/sh -c 'cd "\${APPDIR}/bin";\${APPDIR}/bin/dbus-launch ./trashcan'
EOF

chmod +x ${APPIMAGEFOLDER}/AppRun

ARCH=x86_64 ~/.local/bin/appimagetool-x86_64.AppImage --no-appstream --runtime-file=./runtime-x86_64 ${APPIMAGEFOLDER} ${APPIMAGENAME}.AppImage

#rm -rf "$ELFLOG" "$LIBS"
